Fix: Deprecated artifacts follow up (#153)
*Issue #, if available:*
The previous fix did not work because `download-artifacts@v3` is also
deprecated and must be updated.
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/download-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

Previous fix:
https://github.com/aws-observability/aws-otel-js-instrumentation/pull/152

*Description of changes:*
- Updating `download-artifacts@v3` to `v4`.
- Also fixing syntax error for name pattern.


By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.