add setup-buildx action to release build (#288)
*Issue #, if available:*

*Description of changes:*
The most recent Release build workflow failed:

```
ERROR: failed to build: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
```

Fix by first running
[docker/setup-buildx-action](https://github.com/docker/setup-buildx-action?tab=readme-ov-file#about),
which creates and starts a builder compatible with multi-platform
images.

Tested by using the artifacts_build action, triggered by main build, to
build/push a multi-platform image. Without this step, the action fails
with the same error message as the Release workflow.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.